// -*- c++ -*-

#ifndef __pqSuperquadricGlyphPanel_h
#define __pqSuperquadricGlyphPanel_h

// Qt Includes.
#include <QCheckBox>
#include <QComboBox>
#include <QLabel>
#include <QWidget>
#include <QtDebug>

// ParaView Includes.
#include <pqAutoGeneratedObjectPanel.h>
#include <pqComboBoxDomain.h>
#include <vtkPVConfig.h>


/// Custom panel for SuperquadricGlyph filter.
/// This panel is only provided to add capabilities to hide/gray out
/// GUI elements in case they do not apply and to link the checkbox
/// FixedThetaPhiRoundness to ThetaRoundness/PhiRoundness,
/// HalfAxisVector to HalfAxisVectorArray/HalfAxis*Array,
/// QuatOrientation to Quat*Array/RotationMatrixArray
class pqSuperquadricGlyphPanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT;
  typedef pqAutoGeneratedObjectPanel Superclass;

public:
  pqSuperquadricGlyphPanel(pqProxy *proxy, QWidget *p);

private:

protected:
  QCheckBox *FixedThetaPhiRoundnessWidget;
  QCheckBox *HalfAxisVectorWidget;
  QCheckBox *QuatOrientationWidget;

  QWidget* PhiRoundnessWidget;
  QLabel*  PhiRoundnessLabel;
  QWidget* ThetaRoundnessWidget;
  QLabel*  ThetaRoundnessLabel;

  QWidget* HalfAxisVectorArrayWidget;
  QLabel* HalfAxisVectorArrayLabel;
  QWidget* HalfAxisXArrayWidget;
  QLabel* HalfAxisXArrayLabel;
  QWidget* HalfAxisYArrayWidget;
  QLabel* HalfAxisYArrayLabel;
  QWidget* HalfAxisZArrayWidget;
  QLabel* HalfAxisZArrayLabel;

  QWidget* Quat1ArrayWidget;
  QLabel* Quat1ArrayLabel;
  QWidget* Quat2ArrayWidget;
  QLabel* Quat2ArrayLabel;
  QWidget* Quat3ArrayWidget;
  QLabel* Quat3ArrayLabel;
  QWidget* Quat4ArrayWidget;
  QLabel* Quat4ArrayLabel;
  QWidget* RotationMatrixArrayWidget;
  QLabel* RotationMatrixArrayLabel;

protected slots:

};

#endif //__pqSuperquadricGlyphPanel_h
