# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =  -DLMP_USER_ZOLTAN 
PKG_PATH =  
PKG_LIB =  -lzoltan 

PKG_SYSINC =  
PKG_SYSLIB =  
PKG_SYSPATH = 
